##### This file can be used for Installing Only ISD Components ###############################
# Update the controller URL which needs to be reachable from other clusters where ArgoCD is running
# After installation, the DNS must be updated to point this to EXTERNAL-IP of the agent-grpc service
# kubectl get svc -n opsmx-isd agent-grpc
###################################
forwarder:
  enabled: true
  agent:
    image: quay.io/opsmxpublic/agent-client:v5.1.1
    serviceType: ClusterIP
    # Value is also used in sapor configuration for kubernetes.agent.serverHostName
    host: isd-controller.sandbox.opsmx.net
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: controller-ingress
  image:
    repository: quay.io/opsmxpublic/agent-controller
    tag: v5.1.1
    pullPolicy: IfNotPresent
  serverNames:
    - agent-grpc

  serviceAnnotations: {}
installkeycloak: false


global:
  installOpenLdap: false
  ldap:
    enabled: false
  oesUI:
    # Please below string for all occurences in this file with proper dns entry to access the ISD UI eg: isdui.example.ops.com
    host: isd.sandbox.opsmx.net

  vela:
    # Please below string for all occurences in this file with proper dns entry to access the ISD UI eg: keycloak.example.ops.com$
    host: vela.sandbox.opsmx.net

#######################################################################################################################
# Values of OES Database
db:
  ## Set it to false if any external database is to be used
  enabled: true
  url: jdbc:postgresql://oes-db:5432
  username: postgres
  password: networks123
###############################################################################
## Values of OEA Sapor (Security Audit Policy Onboarding & Release)
sapor:
  ## Image specific details
  image:
    repository: ubi8-oes-sapor
    tag: isd-argo-2025.08.00-368fa618-202507291259
    pullPolicy: IfNotPresent

##################################################################################################################
# Values of Carina Manager
carinamanager:
  ## Image specific details
  ##
  image:
    repository: carina-manager
    tag: v1.15.2
    pullPolicy: IfNotPresent

#######################################################################################################################
# Values of Carina Instance
carinainstance:
  image:
    repository: carina-instance
    tag: v1.14.1
    pullPolicy: IfNotPresent

# Values of Vela
vela:
  image:
    repository: vela-api
    tag: isd-argo-2025.08.00-20250730195
    pullPolicy: IfNotPresent    

## Values of OEA UI
ui:
  ## Image specific details
  image:
    repository: ubi8-oes-ui
    tag: isd-argo-2025.08.00-599a27127-202508130805
    pullPolicy: IfNotPresent

## Values of OEA Autopilot
##
autopilot:
  ## Image specific details
  image:
    repository: ubi8-oes-autopilot
    tag: isd-argo-2025.08.00-9fbe0bbd3-202507291258
    pullPolicy: IfNotPresent

## Values of OEA auditservice
##
audit:
  ## Image specific details
  ##
  image:
    repository: ubi8-oes-audit-service
    tag: isd-argo-2025.08.00-09527cb-202507291258
    pullPolicy: IfNotPresent

## Values of OEA auditclient
##
auditClient:
  ## Image specific details
  ##
  image:
    repository: ubi8-oes-audit-client
    tag: isd-argo-2025.08.00-7b1f0f5-202507291257
    pullPolicy: IfNotPresent

## Values of OEA datascience
##
datascience:
  ## Image specific details
  ##
  image:
    repository: ubi8-oes-datascience
    tag: isd-argo-2025.08.00-9fbe0bbd3-202507291303
    pullPolicy: IfNotPresent

## Values of OEA Dashboard
dashboard:
  ## Image specific details
  image:
    repository: ubi8-oes-dashboard
    tag: isd-argo-2025.08.00-294af4e-202507291259
    pullPolicy: IfNotPresent

## Values of OEA Gate
installOpenLdap: false
##
gate:
  config:
    oauth2:
      enabled: true
      spring:
        security:
          oauth2:
            enabled: true
            login-path: /oauth2/authorization/google
            client:
              registration:
                google:
                  client-id: 59440050702-u9mrh39ngj7unp0uu31si09v15cimvf0.apps.googleusercontent.com
                  client-secret: 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
                  authorization-grant-type: authorization_code
                  redirect-uri: "{baseUrl}/login/oauth2/code/google"
                  scope: profile,email,openid
                  client-name: google
                userInfoRequirements:
                  hd: opsmx.io
              provider:
                google:
                  authorization-uri: https://accounts.google.com/o/oauth2/auth
                  token-uri: https://oauth2.googleapis.com/token
                  user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                  user-name-attribute: sub
  ## Image specific details
  image:
    repository: ubi8-gate
    tag: 669b7bb1-202509090634
    pullPolicy: IfNotPresent

## Values of OEA Platform
platform:
  ## Image specific details
  image:
    repository: ubi8-oes-platform
    tag: isd-argo-2025.08.00-9898ade4-202507291257
    pullPolicy: IfNotPresent    

## Values of OEA Visibility
visibility:
  ## Image specific details
  image:
    repository: ubi8-oes-visibility
    tag: isd-argo-2025.08.00-b2c8eb0-202507291259
    pullPolicy: IfNotPresent

notificationservice:
  ## Image specific details
  ##
  image:
    repository: ubi8-oes-notification-service
    tag: isd-argo-2025.08.00-603dc1d-202507291259
    pullPolicy: IfNotPresent
  host: smtp.gmail.com
  port: 587
  username: REPLACE.YOUR.MAIL.ID
  password: REPLACE.YOUR.MAIL.PASSWORD    

#####User doesn't need to change the below flags let it be the default one######################
installArgoCD: false
######################################################################################
installArgoRollouts: false
#######################################################################################
installdemoapps: false
#######################################################################################
autoconfigureagent: false
#######################################################################################
installkeycloak: false
